# Steps:

Package name/folder
Inside it needs: __init__.py, your_mod.py, setup.py
  the init can be blank
  The mod file will have the functions
  the setup file will have a bunch of stuff, import setuptools, REQUIRED, 

## write the functions in the mod file
  at the bottom of the mod file, you can put the if \_\_name__ == \_\_main__
  use that to test functions before publising them. 
  **check to see if you need to update the version!!!**

## Commit and push changes if everything is working

## Publishing.
  we have to install any of the required packages so that they get added to pip file.
  then we do the build with:`python setup.py sdist bdist_wheel`

  then we publish it with: `twine upload --repository-url https://test.pypi.org/legacy/ dist/*`

  if there are problems we may need to skip an existing with : `twine upload --repository-url https://test.pypi.org/legacy/Â --skip-existing dist/*`

In [1]:
!pip install -i https://test.pypi.org/simple/ erg-lambdata02==0.0.8

Looking in indexes: https://test.pypi.org/simple/
Collecting erg-lambdata02==0.0.8
  Downloading https://test-files.pythonhosted.org/packages/3a/d1/c9ca81f3005cdcf6cc30717283fcbec3195d5660d468c9a27342d09da94c/erg_lambdata02-0.0.8-py3-none-any.whl
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from erg-lambdata02==0.0.8) (1.18.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from erg-lambdata02==0.0.8) (1.0.5)
Requirement already satisfied: sklearn in /usr/local/lib/python3.6/dist-packages (from erg-lambdata02==0.0.8) (0.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas->erg-lambdata02==0.0.8) (2018.9)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas->erg-lambdata02==0.0.8) (2.8.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (from sklearn->erg-lambdata02==0.0.8) (0.22.2.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.6.1->pandas->erg-lambdata02==0.0.8) (1.15.0)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->sklearn->erg-lambdata02==0.0.8) (1.4.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->sklearn->erg-lambdata02==0.0.8) (0.16.0)
Installing collected packages: erg-lambdata02
Successfully installed erg-lambdata02-0.0.8

In [2]:
from lambdata import enzio_ml02

In [3]:
dir(enzio_ml02)

['ErgMLProblemObject',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'pd',
 'sklearn',
 'train_test_split']

In [4]:
enzio_ml02.__package__

'lambdata'

In [5]:
enzio_ml02.sklearn.__package__

'sklearn'

In [6]:
enzio_ml02.sklearn.__name__

'sklearn'

In [7]:
import pandas as pd

In [8]:
def load_twitch_data():
    cols = list(pd.read_csv("twitch_clean_data_Kelly02.csv", nrows=1))
    df = pd.read_csv("twitch_clean_data_Kelly02.csv", parse_dates=["Date"],
                    usecols = [i for i in cols if i !="Unnamed: 71"])
    return df

In [10]:
twitch_original_df = load_twitch_data()

In [11]:
twitch_df = twitch_original_df.copy()

In [12]:
twitch_df.head(2)

        Date  player_mode  ...  avg_message_per_viewer  user_chatting_percent
0 2017-06-13          1.0  ...             12.66666667            66.66666667
1 2017-06-14          1.0  ...                      10            34.61538462

[2 rows x 122 columns]

In [14]:
curr_df = enzio_ml02.ErgMLProblemObject(twitch_df, "Total_Earnings")
curr_df

In [16]:
curr_df.target.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Total_Earnings, dtype: float64

In [17]:
X_matrix, y_target = curr_df.create_xmatrix_ytarget()

NameError: ignored

In [13]:
X_matrix, y_target = enzio_ml02.create_xmatrix_ytarget(twitch_df, "Total_Earnings")

AttributeError: ignored

In [ ]:
X_matrix.head()

        Date  player_mode  ...  avg_message_per_viewer  user_chatting_percent
0 2017-06-13          1.0  ...             12.66666667            66.66666667
1 2017-06-14          1.0  ...                      10            34.61538462
2 2017-06-15          2.0  ...                      40                    300
3 2017-06-16          2.0  ...             2.923076923            38.46153846
4 2017-06-17          2.0  ...             8.333333333            66.66666667

[5 rows x 121 columns]

In [ ]:
y_target.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Total_Earnings, dtype: float64

In [ ]:
enzio_ml.__name__

'lambdata.enzio_ml'

In [ ]:
X_train, X_val, X_test, y_train, y_val, y_test= enzio_ml.train_val_test_split(X_matrix, y_target)

In [ ]:
X_train.head()

          Date  player_mode  ...  avg_message_per_viewer  user_chatting_percent
592 2019-01-26          3.0  ...                     7.5            20.25316456
788 2019-08-10          2.0  ...             3.764044944            33.70786517
537 2018-12-02          2.0  ...             7.675572519            29.77099237
658 2019-04-02          NaN  ...                     inf                    inf
45  2017-07-28          0.0  ...             12.93846154            41.53846154

[5 rows x 121 columns]

In [ ]:
y_val.head(2)

701    4.70
544    2.32
Name: Total_Earnings, dtype: float64

In [ ]:
e